void character_maker_1();
character* character_maker_2(char string[]);
int game();
void get_choice;
void menu();
int map_loader();
void first_place_set();
map_printer();
even_round();
odd_round();
EndOfgame_check();
get_move();
visible();
round_counter();
card_printer();
randomCard_maker();