randomCard_maker();
card_printer();
round_counter();
visible();
get_move();
EndOfgame_check();
odd_round();
even_round();
map_printer();
int map_loader();
void menu();
void get_choice(int choice);
int game();