void prepare_game();
void randomCard_maker();
void even_card_printer();
void odd_card_printer();
int odd_round();
int even_round();
void map_printer();
void map_printer_place(int x, int y);
void map_printer_char(int x, int y);
int map_loader();
int menu();
void info();
int multiplay();
void character_info_printer(int card);
void round_printer();
void first_place_set();
void even_round_linkedlist_creat(card *temp);
void initial_linkedlist();
void card_picker(int card_number, int i);
int card_delete(int choose, int j, card **head);
void possible_moves(int x, int y);
void search_character(int number);
void randomCard_maker_2();
void Mr_jack_CardPicker();
void MrJack_card_show(int number);
void SG_func(int x, int y);
void IL_func(int x, int y);
void WG_func(int x, int y);
void SH_func(int x, int y);
void JB_func(int x, int y);
void JW_func(int x, int y);
void MS_func(int x, int y);
void JS_func(int x, int y);
void make_move(int x, int y, int x_, int y_);
int even_x_moves(int *x_, int *y_, int passed, int init_x, int init_y);
int odd_x_moves(int *x_, int *y_, int passed, int init_x, int init_y);
void show_close_manholes();
void show_open_manholes();
void swap_manholes(int x_, int y_, int x__, int y__);
void manhole_move();
void show_off_lights();
void show_on_lights();
void swap_lights(int x_, int y_, int x__, int y__);
void show_open_gates();
void show_close_gates();
void swap_gates(int x_, int y_, int x__, int y__);
void WG_character_choice(int number);
void WG_character_change(int x, int y, int number);
void swap_characters(int x, int y, int x_, int y_);
void SH_action();
int SG_action1(int number, int x, int y);
int SG_even(int x, int y, int x_, int y_);
int SG_odd(int x, int y, int x_, int y_);
void JW_action();
void visible();
void visible2();
void invalid_func();